=head1 NAME

FlowPDF::Helpers

=head1 AUTHOR

CloudBees

=head1 DESCRIPTION

This module provides various static helper functions.

To use them one should explicitly import them.

=head1 METHODS


=head2 trim

=head3 Description

=head3 Parameters

=head3 Usage



    $str = trim(' hello world ');





=head2 isWin

=head3 Description

Returns true if we're running on windows system.

=head3 Parameters

=over 4

=item None

=back

=head3 Returns

=over 4

=item (Integer) 1 if FlowPDF is running on windows, 0 otherwise.

=back

=head3 Exceptions

=over 4

=item None

=back

=head3 Usage



    if (isWin()) {
        print "This feature is not supported under windows.\n";
    }





=head2 genRandomNumbers

=head3 Description

Generates random numbers using an integer as base. If nothing is passed, 99 will be used as base.

=head3 Parameters

=over 4

=item (Optional)(Integer) - an integer value to be used for random number generation. Can be any integer.

=back

=head3 Returns

=over 4

=item (Integer) A random integer value.

=back

=head3 Exceptions

=over 4

=item None

=back



=head2 bailOut

=head3 Description

Immediately aborts current execution and exits with exit code 1.

This exception can't be handled or catched.

=head3 Parameters

=over 4

=item (Required)(String) An error message to be shown before exiting.

=back

=head3 Returns and Exceptions

=over 4

=item None (this call is fatal).

=back

=head3 Usage



    bailOut("Something is very wrong");





=head2 inArray

=head3 Description

Returns 1 if element is present in array. Currently it works only with scalar elements.

=head3 Parameters

=over 4

=item (Required)(Scalar) Element to check it's presence in array.

=item (Required)(Array of scalars) An array of elements where element presence should be checked.

=back

=head3 Returns

=over 4

=item (Scalar) 1 if element is found in array and 0 if not.

=back

=head3 Exceptions

=over 4

=item Missing parameters exception.

=back

=head3 Usage



    my $elem = 'two';
    my @array = ('one', 'two', 'three');
    if (inArray($elem, @array)) {
        print "$elem is present in array\n";
    }





=cut