pluginInfo:
  pluginName: 'WorkflowWrapper'
  version: '2.0.0'
  description: 'Provides a procedure that launches and monitors a workflow'
  author: 'Tanay Nagjee (FlowPDF by Greg Maxey)'
  supportUrl: 'https://support.cloudbees.com/'
  category: 'Utility'

procedures:
-
  name: 'WorkflowWrapper'
  description: 'Run a workflow and monitor its progress.'
  hasConfig: false
  parameters:
  -
    name: definition_name
    documentation: Name of the workflow definition being launched.
    required: true
    type: entry
    label: Definition Path
  -
    name: definition_parameters
    documentation: >
      Parameters to starting state specified in the format passed to an ec-perl runWorkflow call.  Required parameters to the starting state must be specified or the workflow won't be launched.  Example:

      {actualParameterName => "branch", value => "main"},
      {actualParameterName => "revision", value => 12345},
    required: false
    type: textarea
    label: Definition Parameters
  -
    name: definition_project_name
    documentation: Name of the project containing the workflow definition being launched.
    required: true
    type: entry
    label: Definition Project Name
  -
    name: definition_starting_state
    documentation: Name of the starting state for the workflow definition being launched.
    required: true
    type: entry
    label: Definition Starting State
  -
    name: job_name
    documentation: Name of the wrapper job; defaults to "workflow_wrapper_$[jobId]_$[/timestamp]" if unspecified.
    required: false
    type: entry
    label: Job Name
  steps:
  -
    name: Launch
    shell: ec-perl
  -
    name: Monitor
    shell: ec-perl